"""empty message

Revision ID: 209c38568333
Revises: 89534fae9b97
Create Date: 2024-03-25 20:37:53.550034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '209c38568333'
down_revision = '89534fae9b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('captcha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captcha', sa.String(length=255), nullable=False))
        batch_op.drop_column('temp_captcha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('captcha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_captcha', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('captcha')

    # ### end Alembic commands ###
