# 数据库配置
HOSTNAME="localhost"
PORT=3306
USERNAME="root"
PASSWORD="123456"
DATABASE="temp"
CHARSET="utf8mb4"
# flask只读取下面的配置连接数据库,上面仅是完善下面配置用的
SQLALCHEMY_DATABASE_URI=f"mysql+pymysql://{USERNAME}:{PASSWORD}@{HOSTNAME}:{PORT}/{DATABASE}?charset={CHARSET}"


MAIL_SERVER = 'smtp.126.com'
MAIL_PORT ='465'
MAIL_USE_SSL = True
MAIL_USERNAME = 'cj55555818@126.com'
MAIL_PASSWORD = 'CIULRWIMJCOKGTAF'
MAIL_DEFAULT_SENDER = 'cj55555818@126.com'
SECRET_KEY = "EjpNVSNQTyGi1VvWECj9TvC/+kq3oujee2kTfQUs8yCM6xX9Yjq52v54g+HVoknA"